apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: redis-enterprise-database
spec:
  modulesList:
    - name: search
      version: 2.0.6
    - name: timeseries
      version: 1.4.8
  memorySize: 200MB
